export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const SET_SETTINGS = "SET_SETTINGS";
export const FETCH_SETTINGS = "FETCH_SETTINGS";
export const SET_COMPANY_INFO = "SET_COMPANY_INFO";
export const FETCH_COMPANY_INFO = "FETCH_COMPANY_INFO";
