export const ORG_STRUCTURE = 'orgStructure';
export const PERSPECTIVES = 'perspectives';
export const CASCADE = 'cascade';
export const REVEIEW_PERIOD = 'reviewPeriod';
export const POST = 'post';
export const GET = 'get';
export const PUT = 'put';
export const PATCH = 'patch';
export const AUTHENTICATION_ERROR_MESSAGE = 'Authentication error'
export const RESOURCE_NOT_FOUND_MESSAGE = 'Resource not found'
export const ACTION_SUCCESSFUL_MESSAGE = 'Sucess'
